# Generated by Django 2.2.6 on 2021-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=1000, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_by', models.CharField(max_length=255, verbose_name='创建人')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modified_by', models.CharField(max_length=255, verbose_name='修改人')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='实例名称')),
                ('host', models.CharField(max_length=255, unique=True, verbose_name='主机IP')),
                ('port', models.CharField(max_length=255, verbose_name='端口')),
                ('biz_name', models.CharField(max_length=255, verbose_name='业务名称')),
                ('version', models.CharField(max_length=255, verbose_name='版本')),
                ('status', models.CharField(max_length=255, verbose_name='部署状态')),
                ('deploy_job', models.CharField(max_length=1000, verbose_name='业务名称')),
                ('delete_job', models.CharField(max_length=1000, verbose_name='业务名称')),
            ],
            options={
                'verbose_name': '实例信息',
            },
        ),
    ]
