# Generated by Django 2.2.6 on 2021-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='delete_job',
            field=models.CharField(max_length=1000, verbose_name='删除id'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='deploy_job',
            field=models.CharField(max_length=1000, verbose_name='部署id'),
        ),
    ]
